require 'rails_helper'
require 'pry'
RSpec.describe User, type: :model do
  context 'validation tests' do
    let(:user) { build(:random_user) } # User.new({})
    #let(:user) { create(:user) } # User.create({})
    it 'ensures last_name presence' do
      user.nom = nil
      expect(user.save).to eq(false)
    end
    it 'ensures first_name presence' do
      user.prenom = nil
      expect(user.save).to eq(false)
    end
  end
  #added by ayoub
  it 'the conge_user should be not nil' do
    user = User.new(username: "ayoub")
    user.save
    expect(user.count).to eq(3)

  end



end
#ayoub comment : this model is already generated by mohammed ->steps : first add the gem rspec rails in
#gemfile then run bundle install , creating our two models and run the rails db:migrate
#after we are ready to run bundle exec rspec ... same with the other model "conge"

#or adding another gem called guard rspec to make tests without using the command bundle exec rspec each compilation
#this command with inisialize this gem : bundle exec guard init rspec
